server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: urldelproyectoengit
          search-path: config-data
  application-name: config-service